### ISSUE TITLE
AppDomain.CurrentDomain.BaseDirectory does not end with a slash on Desktop

### ISSUE THREAD

**Issue by ramarag** [dotnet/core-setup#2176]
@ViktorHofer commented on [Wed Apr 12 2017](https://github.com/dotnet/coreclr/issues/10920)

`AppDomain.CurrentDomain.BaseDirectory` does not contain a slash at the end. Failing test in corefx with targetgroup **netfx** here: https://github.com/dotnet/corefx/issues/18196

netfx:
`C:\Users\vikto\Documents\src\corefx\bin\AnyOS.AnyCPU.Debug\System.Configuration.ConfigurationManager.Tests\netstandard`

core:
`C:\Users\vikto\Documents\src\corefx\bin\AnyOS.AnyCPU.Debug\System.Configuration.ConfigurationManager.Tests\netstandard\`

The BaseDirectory property retrieves the path from the GetModuleFileName member from System.Runtime.InteropServices.RuntimeEnvironment in coreclr which itself is declared as extern:
```
[MethodImplAttribute(MethodImplOptions.InternalCall)]
internal static extern String GetModuleFileName();
```

Test executable from corefx project root (build -framework:netfx required before!):
`msbuild src/System.Configuration.ConfigurationManager/tests /t:BuildAndTest /p:targetgroup=netfx /p:xunitoptions="-method System.ConfigurationTests.UrlPathTests.GetDirectoryOrRootName_GettingDirectoryFromAFilePath"`

---

@danmosemsft commented on [Wed Apr 12 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293640981)

@gkhanna79 where would the fix be, on the managed side or native (fusion side)?

---

@gkhanna79 commented on [Wed Apr 12 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293647808)

There is no fusion in CoreCLR. Depending upon how the API is plumbed, it could be in either managed or native.

---

@AlexGhiondea commented on [Wed Apr 12 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293693590)

@gkhanna79 I thought that the host sets this value -- is that true?

---

@gkhanna79 commented on [Wed Apr 12 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293695036)

Feel free to move to Core-Setup and assign to @ramarag if you think the bug is there and not in AD setup code.

---

@AlexGhiondea commented on [Wed Apr 12 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293696775)

I was going off this other comment on a similar issue: https://github.com/dotnet/coreclr/issues/2128#issuecomment-171830617

---

@ViktorHofer commented on [Thu Apr 13 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293715253)

I'm not sure if the bug is in coreclr or in core-setup. I hoped you could answer that.

---

@gkhanna79 commented on [Thu Apr 13 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293919607)

I have a basic question - which is the correct behavior? Desktop or CoreCLR? https://msdn.microsoft.com/en-us/library/system.appdomain.basedirectory(v=vs.110).aspx does not describe the expected behavior.

---

@ViktorHofer commented on [Thu Apr 13 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-293922042)

I think the answer is definitely Desktop as our customers are relying on that behavior since ages...

---

@danmosemsft commented on [Mon Apr 17 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-294561101)

@ViktorHofer could you please attempt to figure out wher ethis bug should go? I agree it is a breaking change we care about. I would like to get it on the right person/repo.

---

@ViktorHofer commented on [Mon Apr 17 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-294582975)

@danmosemsft I will talk to @gkhanna79 and make sure to move the issue to the corresponding team. My bet is - @tarekgh mentioned that too - that the value gets set by the host.

---

@gkhanna79 commented on [Wed Apr 19 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-295362122)

@ramarag Can you PTAL if this is an issue in the host? If not, please send this to @AlexGhiondea 

---

@ViktorHofer commented on [Mon Apr 24 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-296681013)

ping @ramarag 

---

@ramarag commented on [Tue Apr 25 2017](https://github.com/dotnet/coreclr/issues/10920#issuecomment-297188334)

This is a host issue, the logic which returns this value is actually at
https://github.com/dotnet/coreclr/blob/cdff8b0babe5d82737058ccdae8b14d8ae90160d/src/mscorlib/src/System/AppContext/AppContext.cs#L38

**Comment by danmosemsft** [comment]
Where is the fix? Is ("APP_CONTEXT_BASE_DIRECTORY" set somewhere in this repo?

**Comment by danmosemsft** [comment]
Marking as blocking because I think thisi s a potentially important compat issue.

**Comment by ramarag** [comment]
@danmosemsft fix will come from core-setup, you can keep this as a tracking bug if you wish

**Comment by gkhanna79** [comment]
Is it blocking RTM or Preview1? If the latter, why do we think it will be blocking since there is a workaround for it?

**Comment by ramarag** [comment]
This is an appcompat issue, where there is a trailing slash at the end of the string, i would not call it blocking Preview1 but will let @danmosemsft decide on it

**Comment by danmosemsft** [comment]
I meant, I believe we should fix this for RTM. I don't know the best way to mark that in this repo... I guess I won't ..:)

**Comment by danmosemsft** [comment]
@ViktorHofer please keep an  eye out to make sure the test starts passing when we pick up core-setup (and will start failing for netcoreapp .. will need fixing)

**Comment by ViktorHofer** [comment]
Will do. There is a failing test currently in corefx and will check if it stops failing in some days...

**Comment by ViktorHofer** [comment]
@ramarag any idea how long it takes to sync into corefx? Our test is still failing

**Comment by ramarag** [comment]
@ViktorHofer oops just realized that process is not automatic. will put up a PR

**Comment by ViktorHofer** [comment]
@ramarag I think we got a misunderstanding here. The bug was that `AppDomain.Current.BaseDirectory` does not end with a slash on **Desktop**. I just tested the new behavior and now in corefx the slash is also gone. So now with have at least the same behavior between corefx and netfx but not the correct one.

**Netfx behavior (tested in a Console Application with .NET Framework):**
`Console.WriteLine(AppDomain.Current.BaseDirectory)` --> slash at the end

**Core behavior (tested with an unit test inside corefx, before the PR):**
`Console.WriteLine(AppDomain.Current.BaseDirectory)` --> slash at the end

**Desktop behavior (tested with an unit test inside corefx):**
`Console.WriteLine(AppDomain.Current.BaseDirectory)` --> no slash at the end

**Comment by gkhanna79** [comment]
> So now with have at least the same behavior between corefx and netfx but not the correct one.

I am bit confused - are you saying that the original NETFX behavior you called out in the first entry of this issue was incorrect and that .NET Core had the correct behavior? If so, the issue description clearly didn't get that message across which you are just calling out.

If what you are ascertaining to be the expected behaviour in https://github.com/dotnet/core-setup/issues/2176#issuecomment-298925771, then the following needs to happen:

1) @ramarag needs to revert his change in Core-FX and Core-Setup
2) @danmosemsft needs to get the issue fixed for Desktop in AppDomain/IO implementation since that runs against Desktop runtime and not .NET Core, so it is likely an issue in CoreFX.

**Comment by ViktorHofer** [comment]
Believe me, I'm confused too... Just a short recap:

Issue title: 
> AppDomain.CurrentDomain.BaseDirectory  does not end with a slash on Desktop 

Issue description:
> AppDomain.CurrentDomain.BaseDirectory does not contain a slash at the end. Failing test in corefx with targetgroup netfx here

The issue is only happening when running corefx tests with TargetGroup netfx (see the four different behaviors above)

**Comment by gkhanna79** [comment]
@danmosemsft This is not a host bug and should move to CoreFX for someone to look into, especially since it pertains to Desktop only.

@ramarag Can you please revert your CoreFX PR from yesterday (to consume the newer host) and undo the change in Core-Setup?
